name: QodanaCustomImageJob
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: docker pull registry.jetbrains.team/p/sa/containers/qodana-jvm:latest
      - name: Login to Space
        uses: docker/login-action@v2
        with:
          registry: registry.jetbrains.team
          username: Viktor.Tiulpin
          password: ${{ secrets.SPACE_PASSWORD }}
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v5.1.0
        with:
          args: "--linter,registry.jetbrains.team/p/sa/containers/qodana-jvm:latest"
      - name: 'Deploy to GitHub Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ runner.temp }}/qodana/results/report
          destination_dir: ./
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ runner.temp }}/qodana/results/


